### ISSUE TITLE
oei_attest_begin

### ISSUE THREAD

**Issue by boofish** [RiS3-Lab/OAT-Project#1]
Hello, I am very interested in OAT and I think it is a great job.
However, I encounter some difficulties when reproducing the work.
When I try to attest an operation function `main()` at `oat-test/test-sensitive-variables` by using ( `#oei_attest_begin` , `#oei_attest_end`) tag, it seems it does not work as expected. In practice,  the compiler will report an error. 
Any ideas?

**Comment by sunzc** [comment]
You can refer to this [example](https://github.com/RiS3-Lab/OAT-Project/blob/107c69a7f56ae7400ddef6431ff947fc9823f61e/oat-trampoline-lib/microbench.c) and replace `#oei_attest_begin` with `cfv_init();` and `#oei_attest_end` with `cfv_quote();`.

**Comment by boofish** [comment]
Thank you very much, I got it!
