### ISSUE TITLE
How to install OAT compiler

### ISSUE THREAD

**Issue by esaurimentocronico** [RiS3-Lab/OAT-Project#2]
Hi,

I'm studying control-flow attestation in embedded devices focusing on your work which is very interesting. In order to test your work i have been trying to install the oat compiler but i can not. Can you please help me step by step to install it ? Thank yo so much.
 
Here is my questions:

1-  I downloaded the latest version of cmake from (https://cmake.org/download/) and then i installed it following these instructions (https://cmake.org/install/) . Then i was wondering what the build directory should be. Should it be ad independent directory or the cmake directory inside the oat-llvm40 directory ?

Thank you

**Comment by sunzc** [comment]
Hi there,

You can refer to the Quick Start section in this doc: https://github.com/RiS3-Lab/OAT-Project/blob/master/oat-llvm40/docs/CMake.rst

Let me know if you have any further questions.

- Zhichuang

**Comment by esaurimentocronico** [comment]
> Hi there,
> 
> You can refer to the Quick Start section in this doc: https://github.com/RiS3-Lab/OAT-Project/blob/master/oat-llvm40/docs/CMake.rst
> 
> Let me know if you have any further questions.
> 
>     * Zhichuang

**Comment by esaurimentocronico** [comment]
> Hi there,
> 
> You can refer to the Quick Start section in this doc: https://github.com/RiS3-Lab/OAT-Project/blob/master/oat-llvm40/docs/CMake.rst
> 
> Let me know if you have any further questions.
> 
>     * Zhichuang

Should the build directory be an independent directory or a directory within oat-llvm directory ?

Thank you

**Comment by sunzc** [comment]
> > Hi there,
> > You can refer to the Quick Start section in this doc: https://github.com/RiS3-Lab/OAT-Project/blob/master/oat-llvm40/docs/CMake.rst
> > Let me know if you have any further questions.
> > ```
> > * Zhichuang
> > ```
> 
> Should the build directory be an independent directory or a directory within oat-llvm directory ?
> 
> Thank you

You should create one outside the source directory. Like:
`mkdir build`

**Comment by esaurimentocronico** [comment]
> > > Hi there,
> > > You can refer to the Quick Start section in this doc: https://github.com/RiS3-Lab/OAT-Project/blob/master/oat-llvm40/docs/CMake.rst
> > > Let me know if you have any further questions.
> > > ```
> > > * Zhichuang
> > > ```
> > 
> > 
> > Should the build directory be an independent directory or a directory within oat-llvm directory ?
> > Thank you
> 
> You should create one outside the source directory. Like:
> `mkdir build`

Ok i got it, so for the step number 4 should i download the llvm source code or all necessary files are inside the oat folder ?

**Comment by sunzc** [comment]
> Ok i got it, so for the step number 4 should i download the llvm source code or all necessary files are inside the oat folder ?

oat-llvm40/ is the source repo for llvm, you should use it.

**Comment by esaurimentocronico** [comment]
> > Ok i got it, so for the step number 4 should i download the llvm source code or all necessary files are inside the oat folder ?
> 
> oat-llvm40/ is the source repo for llvm, you should use it.

Yes, i did it! First i created the foder `mkdir build`, after that cd to this directory: `cd build` and then i run the command `cmake path/to/oat-llvm40`. However after CMake has finished running, i tried to run `cmake --build` command within the build directory but i got these messagge `Usage: cmake --build <dir> [options] [-- [native-options]]`

**Comment by esaurimentocronico** [comment]
> > Ok i got it, so for the step number 4 should i download the llvm source code or all necessary files are inside the oat folder ?
> 
> oat-llvm40/ is the source repo for llvm, you should use it.

Yes, i didi it! However when i build the llvm using the command 'cmake --build .' i got this error message : 

`[ 62%] Linking CXX shared library ../../lib/libLTO.so
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
tools/lto/CMakeFiles/LTO.dir/build.make:261: recipe for target 'lib/libLTO.so.4.0.0' failed
make[2]: *** [lib/libLTO.so.4.0.0] Error 1
make[2]: *** Deleting file 'lib/libLTO.so.4.0.0'
CMakeFiles/Makefile2:15272: recipe for target 'tools/lto/CMakeFiles/LTO.dir/all' failed
make[1]: *** [tools/lto/CMakeFiles/LTO.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
`

Thank you.

**Comment by sunzc** [comment]
Can you double-check that you basically followed the following sequence?
```
#Assume you are in the current directory of OAT-Project/
mkdir build
cd build
cmake ../oat-llvm40/
cmake --build .
```
Btw, when you run `cmake ../oat-llvm40/`,  is there any warnings or errors?

**Comment by esaurimentocronico** [comment]
> Can you double-check that you basically followed the following sequence?
> 
> ```
> #Assume you are in the current directory of OAT-Project/
> mkdir build
> cd build
> cmake ../oat-llvm40/
> cmake --build .
> ```
> 
> Btw, when you run `cmake ../oat-llvm40/`, is there any warnings or errors?

No there is not. I think it is a problem of memory exhaustion on the server
