### ISSUE TITLE
can not found telldus-core

### ISSUE THREAD

**Issue by boofish** [RiS3-Lab/OAT-Project#4]
Hello, I encountered a problem when compiling the project `light-controller-cb`,

the error message is 
```
light-controller.c:25:10: fatal error: 'telldus-core.h' file not found
```

I think it is related to a lib named `ltelldus-core` for its defined in the makefile `LDLIBS := -ltelldus-core -rdynamic` and the corresponding path is `TD=~/work/telldus-core/telldus-core-2.1.2/tdtool/`

However, I have trouble downloading such a lib, for example, 
I have found the link https://pkgs.org/download/telldus-core, but it does not work for me.

Could you please attach it to the repository?

**Comment by sunzc** [comment]
Could you try [this](https://developer.telldus.com/wiki/TellStickInstallationSource) ?

Here is the original git repo for light-controller : https://github.com/Barro/light-controller. Maybe you should try to get it run first (following the original instructions) before you try to apply OAT. The same tip for other evaluation applications (see the paper for the github repo link). Hoping it will make things easier.

**Comment by boofish** [comment]
Thank you very much!
